package com.ydb.mapper.nochange;

import com.ydb.entity.nochange.Issue;
import com.ydb.entity.nochange.IssueExample;
import com.ydb.entity.nochange.IssueWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int countByExample(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int deleteByExample(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int insert(IssueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int insertSelective(IssueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    List<IssueWithBLOBs> selectByExampleWithBLOBs(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    List<Issue> selectByExample(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    IssueWithBLOBs selectByPrimaryKey(String UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IssueWithBLOBs record, @Param("example") IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") IssueWithBLOBs record, @Param("example") IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Issue record, @Param("example") IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IssueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(IssueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Issue record);
}