package com.ydb.mapper.nochange;

import com.ydb.entity.nochange.Issue;
import com.ydb.entity.nochange.IssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    long countByExample(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int deleteByExample(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int insert(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int insertSelective(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    List<Issue> selectByExampleWithBLOBs(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    List<Issue> selectByExample(IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    Issue selectByPrimaryKey(String UID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Issue record, @Param("example") IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Issue record, @Param("example") IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Issue record, @Param("example") IssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Issue record);
}