package com.ydb.entity.nochange;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IssueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Issues
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Issues
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Issues
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public IssueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Issues
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUIDIsNull() {
            addCriterion("UID is null");
            return (Criteria) this;
        }

        public Criteria andUIDIsNotNull() {
            addCriterion("UID is not null");
            return (Criteria) this;
        }

        public Criteria andUIDEqualTo(String value) {
            addCriterion("UID =", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotEqualTo(String value) {
            addCriterion("UID <>", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThan(String value) {
            addCriterion("UID >", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThanOrEqualTo(String value) {
            addCriterion("UID >=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThan(String value) {
            addCriterion("UID <", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThanOrEqualTo(String value) {
            addCriterion("UID <=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLike(String value) {
            addCriterion("UID like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotLike(String value) {
            addCriterion("UID not like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDIn(List<String> values) {
            addCriterion("UID in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotIn(List<String> values) {
            addCriterion("UID not in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDBetween(String value1, String value2) {
            addCriterion("UID between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotBetween(String value1, String value2) {
            addCriterion("UID not between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNull() {
            addCriterion("UserID is null");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNotNull() {
            addCriterion("UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIDEqualTo(Long value) {
            addCriterion("UserID =", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotEqualTo(Long value) {
            addCriterion("UserID <>", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThan(Long value) {
            addCriterion("UserID >", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThanOrEqualTo(Long value) {
            addCriterion("UserID >=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThan(Long value) {
            addCriterion("UserID <", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThanOrEqualTo(Long value) {
            addCriterion("UserID <=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDIn(List<Long> values) {
            addCriterion("UserID in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotIn(List<Long> values) {
            addCriterion("UserID not in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDBetween(Long value1, Long value2) {
            addCriterion("UserID between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotBetween(Long value1, Long value2) {
            addCriterion("UserID not between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("Type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("Type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("Type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("Type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("Type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("Type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("Type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("Type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("Type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("Type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("Type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIsShareIsNull() {
            addCriterion("IsShare is null");
            return (Criteria) this;
        }

        public Criteria andIsShareIsNotNull() {
            addCriterion("IsShare is not null");
            return (Criteria) this;
        }

        public Criteria andIsShareEqualTo(Boolean value) {
            addCriterion("IsShare =", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareNotEqualTo(Boolean value) {
            addCriterion("IsShare <>", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareGreaterThan(Boolean value) {
            addCriterion("IsShare >", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsShare >=", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareLessThan(Boolean value) {
            addCriterion("IsShare <", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareLessThanOrEqualTo(Boolean value) {
            addCriterion("IsShare <=", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareIn(List<Boolean> values) {
            addCriterion("IsShare in", values, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareNotIn(List<Boolean> values) {
            addCriterion("IsShare not in", values, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareBetween(Boolean value1, Boolean value2) {
            addCriterion("IsShare between", value1, value2, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsShare not between", value1, value2, "isShare");
            return (Criteria) this;
        }

        public Criteria andShareUserIDIsNull() {
            addCriterion("shareUserID is null");
            return (Criteria) this;
        }

        public Criteria andShareUserIDIsNotNull() {
            addCriterion("shareUserID is not null");
            return (Criteria) this;
        }

        public Criteria andShareUserIDEqualTo(Long value) {
            addCriterion("shareUserID =", value, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDNotEqualTo(Long value) {
            addCriterion("shareUserID <>", value, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDGreaterThan(Long value) {
            addCriterion("shareUserID >", value, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDGreaterThanOrEqualTo(Long value) {
            addCriterion("shareUserID >=", value, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDLessThan(Long value) {
            addCriterion("shareUserID <", value, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDLessThanOrEqualTo(Long value) {
            addCriterion("shareUserID <=", value, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDIn(List<Long> values) {
            addCriterion("shareUserID in", values, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDNotIn(List<Long> values) {
            addCriterion("shareUserID not in", values, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDBetween(Long value1, Long value2) {
            addCriterion("shareUserID between", value1, value2, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andShareUserIDNotBetween(Long value1, Long value2) {
            addCriterion("shareUserID not between", value1, value2, "shareUserID");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("Sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("Sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Short value) {
            addCriterion("Sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Short value) {
            addCriterion("Sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Short value) {
            addCriterion("Sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Short value) {
            addCriterion("Sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Short value) {
            addCriterion("Sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Short value) {
            addCriterion("Sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Short> values) {
            addCriterion("Sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Short> values) {
            addCriterion("Sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Short value1, Short value2) {
            addCriterion("Sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Short value1, Short value2) {
            addCriterion("Sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andPraiseNumIsNull() {
            addCriterion("PraiseNum is null");
            return (Criteria) this;
        }

        public Criteria andPraiseNumIsNotNull() {
            addCriterion("PraiseNum is not null");
            return (Criteria) this;
        }

        public Criteria andPraiseNumEqualTo(Short value) {
            addCriterion("PraiseNum =", value, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumNotEqualTo(Short value) {
            addCriterion("PraiseNum <>", value, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumGreaterThan(Short value) {
            addCriterion("PraiseNum >", value, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumGreaterThanOrEqualTo(Short value) {
            addCriterion("PraiseNum >=", value, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumLessThan(Short value) {
            addCriterion("PraiseNum <", value, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumLessThanOrEqualTo(Short value) {
            addCriterion("PraiseNum <=", value, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumIn(List<Short> values) {
            addCriterion("PraiseNum in", values, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumNotIn(List<Short> values) {
            addCriterion("PraiseNum not in", values, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumBetween(Short value1, Short value2) {
            addCriterion("PraiseNum between", value1, value2, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andPraiseNumNotBetween(Short value1, Short value2) {
            addCriterion("PraiseNum not between", value1, value2, "praiseNum");
            return (Criteria) this;
        }

        public Criteria andReadNumIsNull() {
            addCriterion("ReadNum is null");
            return (Criteria) this;
        }

        public Criteria andReadNumIsNotNull() {
            addCriterion("ReadNum is not null");
            return (Criteria) this;
        }

        public Criteria andReadNumEqualTo(Short value) {
            addCriterion("ReadNum =", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumNotEqualTo(Short value) {
            addCriterion("ReadNum <>", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumGreaterThan(Short value) {
            addCriterion("ReadNum >", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumGreaterThanOrEqualTo(Short value) {
            addCriterion("ReadNum >=", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumLessThan(Short value) {
            addCriterion("ReadNum <", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumLessThanOrEqualTo(Short value) {
            addCriterion("ReadNum <=", value, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumIn(List<Short> values) {
            addCriterion("ReadNum in", values, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumNotIn(List<Short> values) {
            addCriterion("ReadNum not in", values, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumBetween(Short value1, Short value2) {
            addCriterion("ReadNum between", value1, value2, "readNum");
            return (Criteria) this;
        }

        public Criteria andReadNumNotBetween(Short value1, Short value2) {
            addCriterion("ReadNum not between", value1, value2, "readNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumIsNull() {
            addCriterion("CollectNum is null");
            return (Criteria) this;
        }

        public Criteria andCollectNumIsNotNull() {
            addCriterion("CollectNum is not null");
            return (Criteria) this;
        }

        public Criteria andCollectNumEqualTo(Short value) {
            addCriterion("CollectNum =", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumNotEqualTo(Short value) {
            addCriterion("CollectNum <>", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumGreaterThan(Short value) {
            addCriterion("CollectNum >", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumGreaterThanOrEqualTo(Short value) {
            addCriterion("CollectNum >=", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumLessThan(Short value) {
            addCriterion("CollectNum <", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumLessThanOrEqualTo(Short value) {
            addCriterion("CollectNum <=", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumIn(List<Short> values) {
            addCriterion("CollectNum in", values, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumNotIn(List<Short> values) {
            addCriterion("CollectNum not in", values, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumBetween(Short value1, Short value2) {
            addCriterion("CollectNum between", value1, value2, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumNotBetween(Short value1, Short value2) {
            addCriterion("CollectNum not between", value1, value2, "collectNum");
            return (Criteria) this;
        }

        public Criteria andHotNumIsNull() {
            addCriterion("HotNum is null");
            return (Criteria) this;
        }

        public Criteria andHotNumIsNotNull() {
            addCriterion("HotNum is not null");
            return (Criteria) this;
        }

        public Criteria andHotNumEqualTo(Date value) {
            addCriterion("HotNum =", value, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumNotEqualTo(Date value) {
            addCriterion("HotNum <>", value, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumGreaterThan(Date value) {
            addCriterion("HotNum >", value, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumGreaterThanOrEqualTo(Date value) {
            addCriterion("HotNum >=", value, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumLessThan(Date value) {
            addCriterion("HotNum <", value, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumLessThanOrEqualTo(Date value) {
            addCriterion("HotNum <=", value, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumIn(List<Date> values) {
            addCriterion("HotNum in", values, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumNotIn(List<Date> values) {
            addCriterion("HotNum not in", values, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumBetween(Date value1, Date value2) {
            addCriterion("HotNum between", value1, value2, "hotNum");
            return (Criteria) this;
        }

        public Criteria andHotNumNotBetween(Date value1, Date value2) {
            addCriterion("HotNum not between", value1, value2, "hotNum");
            return (Criteria) this;
        }

        public Criteria andIsPublicIsNull() {
            addCriterion("IsPublic is null");
            return (Criteria) this;
        }

        public Criteria andIsPublicIsNotNull() {
            addCriterion("IsPublic is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublicEqualTo(Boolean value) {
            addCriterion("IsPublic =", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicNotEqualTo(Boolean value) {
            addCriterion("IsPublic <>", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicGreaterThan(Boolean value) {
            addCriterion("IsPublic >", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsPublic >=", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicLessThan(Boolean value) {
            addCriterion("IsPublic <", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicLessThanOrEqualTo(Boolean value) {
            addCriterion("IsPublic <=", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicIn(List<Boolean> values) {
            addCriterion("IsPublic in", values, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicNotIn(List<Boolean> values) {
            addCriterion("IsPublic not in", values, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicBetween(Boolean value1, Boolean value2) {
            addCriterion("IsPublic between", value1, value2, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsPublic not between", value1, value2, "isPublic");
            return (Criteria) this;
        }

        public Criteria andAnswerNumIsNull() {
            addCriterion("AnswerNum is null");
            return (Criteria) this;
        }

        public Criteria andAnswerNumIsNotNull() {
            addCriterion("AnswerNum is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerNumEqualTo(Short value) {
            addCriterion("AnswerNum =", value, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumNotEqualTo(Short value) {
            addCriterion("AnswerNum <>", value, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumGreaterThan(Short value) {
            addCriterion("AnswerNum >", value, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumGreaterThanOrEqualTo(Short value) {
            addCriterion("AnswerNum >=", value, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumLessThan(Short value) {
            addCriterion("AnswerNum <", value, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumLessThanOrEqualTo(Short value) {
            addCriterion("AnswerNum <=", value, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumIn(List<Short> values) {
            addCriterion("AnswerNum in", values, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumNotIn(List<Short> values) {
            addCriterion("AnswerNum not in", values, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumBetween(Short value1, Short value2) {
            addCriterion("AnswerNum between", value1, value2, "answerNum");
            return (Criteria) this;
        }

        public Criteria andAnswerNumNotBetween(Short value1, Short value2) {
            addCriterion("AnswerNum not between", value1, value2, "answerNum");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("Tags is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("Tags is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("Tags =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("Tags <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("Tags >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("Tags >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("Tags <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("Tags <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("Tags like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("Tags not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("Tags in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("Tags not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("Tags between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("Tags not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UpdateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UpdateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andActiveIdIsNull() {
            addCriterion("ActiveId is null");
            return (Criteria) this;
        }

        public Criteria andActiveIdIsNotNull() {
            addCriterion("ActiveId is not null");
            return (Criteria) this;
        }

        public Criteria andActiveIdEqualTo(Long value) {
            addCriterion("ActiveId =", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdNotEqualTo(Long value) {
            addCriterion("ActiveId <>", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdGreaterThan(Long value) {
            addCriterion("ActiveId >", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ActiveId >=", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdLessThan(Long value) {
            addCriterion("ActiveId <", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdLessThanOrEqualTo(Long value) {
            addCriterion("ActiveId <=", value, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdIn(List<Long> values) {
            addCriterion("ActiveId in", values, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdNotIn(List<Long> values) {
            addCriterion("ActiveId not in", values, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdBetween(Long value1, Long value2) {
            addCriterion("ActiveId between", value1, value2, "activeId");
            return (Criteria) this;
        }

        public Criteria andActiveIdNotBetween(Long value1, Long value2) {
            addCriterion("ActiveId not between", value1, value2, "activeId");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNull() {
            addCriterion("TeamId is null");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNotNull() {
            addCriterion("TeamId is not null");
            return (Criteria) this;
        }

        public Criteria andTeamIdEqualTo(Integer value) {
            addCriterion("TeamId =", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotEqualTo(Integer value) {
            addCriterion("TeamId <>", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThan(Integer value) {
            addCriterion("TeamId >", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TeamId >=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThan(Integer value) {
            addCriterion("TeamId <", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThanOrEqualTo(Integer value) {
            addCriterion("TeamId <=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdIn(List<Integer> values) {
            addCriterion("TeamId in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotIn(List<Integer> values) {
            addCriterion("TeamId not in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdBetween(Integer value1, Integer value2) {
            addCriterion("TeamId between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TeamId not between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDIsNull() {
            addCriterion("LastAnswerID is null");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDIsNotNull() {
            addCriterion("LastAnswerID is not null");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDEqualTo(String value) {
            addCriterion("LastAnswerID =", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDNotEqualTo(String value) {
            addCriterion("LastAnswerID <>", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDGreaterThan(String value) {
            addCriterion("LastAnswerID >", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDGreaterThanOrEqualTo(String value) {
            addCriterion("LastAnswerID >=", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDLessThan(String value) {
            addCriterion("LastAnswerID <", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDLessThanOrEqualTo(String value) {
            addCriterion("LastAnswerID <=", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDLike(String value) {
            addCriterion("LastAnswerID like", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDNotLike(String value) {
            addCriterion("LastAnswerID not like", value, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDIn(List<String> values) {
            addCriterion("LastAnswerID in", values, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDNotIn(List<String> values) {
            addCriterion("LastAnswerID not in", values, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDBetween(String value1, String value2) {
            addCriterion("LastAnswerID between", value1, value2, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andLastAnswerIDNotBetween(String value1, String value2) {
            addCriterion("LastAnswerID not between", value1, value2, "lastAnswerID");
            return (Criteria) this;
        }

        public Criteria andReviewNumIsNull() {
            addCriterion("ReviewNum is null");
            return (Criteria) this;
        }

        public Criteria andReviewNumIsNotNull() {
            addCriterion("ReviewNum is not null");
            return (Criteria) this;
        }

        public Criteria andReviewNumEqualTo(Short value) {
            addCriterion("ReviewNum =", value, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumNotEqualTo(Short value) {
            addCriterion("ReviewNum <>", value, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumGreaterThan(Short value) {
            addCriterion("ReviewNum >", value, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumGreaterThanOrEqualTo(Short value) {
            addCriterion("ReviewNum >=", value, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumLessThan(Short value) {
            addCriterion("ReviewNum <", value, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumLessThanOrEqualTo(Short value) {
            addCriterion("ReviewNum <=", value, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumIn(List<Short> values) {
            addCriterion("ReviewNum in", values, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumNotIn(List<Short> values) {
            addCriterion("ReviewNum not in", values, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumBetween(Short value1, Short value2) {
            addCriterion("ReviewNum between", value1, value2, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andReviewNumNotBetween(Short value1, Short value2) {
            addCriterion("ReviewNum not between", value1, value2, "reviewNum");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousIsNull() {
            addCriterion("IsAnonyMous is null");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousIsNotNull() {
            addCriterion("IsAnonyMous is not null");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousEqualTo(Boolean value) {
            addCriterion("IsAnonyMous =", value, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousNotEqualTo(Boolean value) {
            addCriterion("IsAnonyMous <>", value, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousGreaterThan(Boolean value) {
            addCriterion("IsAnonyMous >", value, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsAnonyMous >=", value, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousLessThan(Boolean value) {
            addCriterion("IsAnonyMous <", value, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousLessThanOrEqualTo(Boolean value) {
            addCriterion("IsAnonyMous <=", value, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousIn(List<Boolean> values) {
            addCriterion("IsAnonyMous in", values, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousNotIn(List<Boolean> values) {
            addCriterion("IsAnonyMous not in", values, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousBetween(Boolean value1, Boolean value2) {
            addCriterion("IsAnonyMous between", value1, value2, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andIsAnonyMousNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsAnonyMous not between", value1, value2, "isAnonyMous");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("Sequence is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("Sequence is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(Long value) {
            addCriterion("Sequence =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(Long value) {
            addCriterion("Sequence <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(Long value) {
            addCriterion("Sequence >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Long value) {
            addCriterion("Sequence >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(Long value) {
            addCriterion("Sequence <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Long value) {
            addCriterion("Sequence <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<Long> values) {
            addCriterion("Sequence in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<Long> values) {
            addCriterion("Sequence not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(Long value1, Long value2) {
            addCriterion("Sequence between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(Long value1, Long value2) {
            addCriterion("Sequence not between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdIsNull() {
            addCriterion("originalIssueId is null");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdIsNotNull() {
            addCriterion("originalIssueId is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdEqualTo(String value) {
            addCriterion("originalIssueId =", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdNotEqualTo(String value) {
            addCriterion("originalIssueId <>", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdGreaterThan(String value) {
            addCriterion("originalIssueId >", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdGreaterThanOrEqualTo(String value) {
            addCriterion("originalIssueId >=", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdLessThan(String value) {
            addCriterion("originalIssueId <", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdLessThanOrEqualTo(String value) {
            addCriterion("originalIssueId <=", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdLike(String value) {
            addCriterion("originalIssueId like", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdNotLike(String value) {
            addCriterion("originalIssueId not like", value, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdIn(List<String> values) {
            addCriterion("originalIssueId in", values, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdNotIn(List<String> values) {
            addCriterion("originalIssueId not in", values, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdBetween(String value1, String value2) {
            addCriterion("originalIssueId between", value1, value2, "originalIssueId");
            return (Criteria) this;
        }

        public Criteria andOriginalIssueIdNotBetween(String value1, String value2) {
            addCriterion("originalIssueId not between", value1, value2, "originalIssueId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Issues
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Issues
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}