package com.ydb.entity.nochange;

import com.ydb.entity.BaseEntity;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Issues
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Issue extends BaseEntity {
    /**
     * Database Column Remarks:
     *   这是主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UID
     *
     * @mbg.generated
     */
    private String UID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UserID
     *
     * @mbg.generated
     */
    private Long userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.IsShare
     *
     * @mbg.generated
     */
    private Boolean isShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.shareUserID
     *
     * @mbg.generated
     */
    private Long shareUserID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.PraiseNum
     *
     * @mbg.generated
     */
    private Short praiseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ReadNum
     *
     * @mbg.generated
     */
    private Short readNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.CollectNum
     *
     * @mbg.generated
     */
    private Short collectNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.HotNum
     *
     * @mbg.generated
     */
    private Date hotNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.IsPublic
     *
     * @mbg.generated
     */
    private Boolean isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.AnswerNum
     *
     * @mbg.generated
     */
    private Short answerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UpdateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.CreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ActiveId
     *
     * @mbg.generated
     */
    private Long activeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.TeamId
     *
     * @mbg.generated
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.LastAnswerID
     *
     * @mbg.generated
     */
    private String lastAnswerID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ReviewNum
     *
     * @mbg.generated
     */
    private Short reviewNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.IsAnonyMous
     *
     * @mbg.generated
     */
    private Boolean isAnonyMous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Sequence
     *
     * @mbg.generated
     */
    private Long sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.originalIssueId
     *
     * @mbg.generated
     */
    private String originalIssueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UserInfo
     *
     * @mbg.generated
     */
    private String userInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ToUser
     *
     * @mbg.generated
     */
    private String toUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.FromTeam
     *
     * @mbg.generated
     */
    private String fromTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ToTeam
     *
     * @mbg.generated
     */
    private String toTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ShareUser
     *
     * @mbg.generated
     */
    private String shareUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Feedback
     *
     * @mbg.generated
     */
    private String feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Audios
     *
     * @mbg.generated
     */
    private String audios;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Invited
     *
     * @mbg.generated
     */
    private String invited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.AdditionActivity
     *
     * @mbg.generated
     */
    private String additionActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.AdditionTeam
     *
     * @mbg.generated
     */
    private String additionTeam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UID
     *
     * @return the value of Issues.UID
     *
     * @mbg.generated
     */
    public String getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UID
     *
     * @param UID the value for Issues.UID
     *
     * @mbg.generated
     */
    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UserID
     *
     * @return the value of Issues.UserID
     *
     * @mbg.generated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UserID
     *
     * @param userID the value for Issues.UserID
     *
     * @mbg.generated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Type
     *
     * @return the value of Issues.Type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Type
     *
     * @param type the value for Issues.Type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Title
     *
     * @return the value of Issues.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Title
     *
     * @param title the value for Issues.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.IsShare
     *
     * @return the value of Issues.IsShare
     *
     * @mbg.generated
     */
    public Boolean getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.IsShare
     *
     * @param isShare the value for Issues.IsShare
     *
     * @mbg.generated
     */
    public void setIsShare(Boolean isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.shareUserID
     *
     * @return the value of Issues.shareUserID
     *
     * @mbg.generated
     */
    public Long getShareUserID() {
        return shareUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.shareUserID
     *
     * @param shareUserID the value for Issues.shareUserID
     *
     * @mbg.generated
     */
    public void setShareUserID(Long shareUserID) {
        this.shareUserID = shareUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Sort
     *
     * @return the value of Issues.Sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Sort
     *
     * @param sort the value for Issues.Sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.PraiseNum
     *
     * @return the value of Issues.PraiseNum
     *
     * @mbg.generated
     */
    public Short getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.PraiseNum
     *
     * @param praiseNum the value for Issues.PraiseNum
     *
     * @mbg.generated
     */
    public void setPraiseNum(Short praiseNum) {
        this.praiseNum = praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ReadNum
     *
     * @return the value of Issues.ReadNum
     *
     * @mbg.generated
     */
    public Short getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ReadNum
     *
     * @param readNum the value for Issues.ReadNum
     *
     * @mbg.generated
     */
    public void setReadNum(Short readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.CollectNum
     *
     * @return the value of Issues.CollectNum
     *
     * @mbg.generated
     */
    public Short getCollectNum() {
        return collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.CollectNum
     *
     * @param collectNum the value for Issues.CollectNum
     *
     * @mbg.generated
     */
    public void setCollectNum(Short collectNum) {
        this.collectNum = collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.HotNum
     *
     * @return the value of Issues.HotNum
     *
     * @mbg.generated
     */
    public Date getHotNum() {
        return hotNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.HotNum
     *
     * @param hotNum the value for Issues.HotNum
     *
     * @mbg.generated
     */
    public void setHotNum(Date hotNum) {
        this.hotNum = hotNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.IsPublic
     *
     * @return the value of Issues.IsPublic
     *
     * @mbg.generated
     */
    public Boolean getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.IsPublic
     *
     * @param isPublic the value for Issues.IsPublic
     *
     * @mbg.generated
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.AnswerNum
     *
     * @return the value of Issues.AnswerNum
     *
     * @mbg.generated
     */
    public Short getAnswerNum() {
        return answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.AnswerNum
     *
     * @param answerNum the value for Issues.AnswerNum
     *
     * @mbg.generated
     */
    public void setAnswerNum(Short answerNum) {
        this.answerNum = answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Tags
     *
     * @return the value of Issues.Tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Tags
     *
     * @param tags the value for Issues.Tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Status
     *
     * @return the value of Issues.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Status
     *
     * @param status the value for Issues.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UpdateTime
     *
     * @return the value of Issues.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UpdateTime
     *
     * @param updateTime the value for Issues.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.CreateTime
     *
     * @return the value of Issues.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.CreateTime
     *
     * @param createTime the value for Issues.CreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ActiveId
     *
     * @return the value of Issues.ActiveId
     *
     * @mbg.generated
     */
    public Long getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ActiveId
     *
     * @param activeId the value for Issues.ActiveId
     *
     * @mbg.generated
     */
    public void setActiveId(Long activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.TeamId
     *
     * @return the value of Issues.TeamId
     *
     * @mbg.generated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.TeamId
     *
     * @param teamId the value for Issues.TeamId
     *
     * @mbg.generated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.LastAnswerID
     *
     * @return the value of Issues.LastAnswerID
     *
     * @mbg.generated
     */
    public String getLastAnswerID() {
        return lastAnswerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.LastAnswerID
     *
     * @param lastAnswerID the value for Issues.LastAnswerID
     *
     * @mbg.generated
     */
    public void setLastAnswerID(String lastAnswerID) {
        this.lastAnswerID = lastAnswerID == null ? null : lastAnswerID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ReviewNum
     *
     * @return the value of Issues.ReviewNum
     *
     * @mbg.generated
     */
    public Short getReviewNum() {
        return reviewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ReviewNum
     *
     * @param reviewNum the value for Issues.ReviewNum
     *
     * @mbg.generated
     */
    public void setReviewNum(Short reviewNum) {
        this.reviewNum = reviewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.IsAnonyMous
     *
     * @return the value of Issues.IsAnonyMous
     *
     * @mbg.generated
     */
    public Boolean getIsAnonyMous() {
        return isAnonyMous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.IsAnonyMous
     *
     * @param isAnonyMous the value for Issues.IsAnonyMous
     *
     * @mbg.generated
     */
    public void setIsAnonyMous(Boolean isAnonyMous) {
        this.isAnonyMous = isAnonyMous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Sequence
     *
     * @return the value of Issues.Sequence
     *
     * @mbg.generated
     */
    public Long getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Sequence
     *
     * @param sequence the value for Issues.Sequence
     *
     * @mbg.generated
     */
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.originalIssueId
     *
     * @return the value of Issues.originalIssueId
     *
     * @mbg.generated
     */
    public String getOriginalIssueId() {
        return originalIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.originalIssueId
     *
     * @param originalIssueId the value for Issues.originalIssueId
     *
     * @mbg.generated
     */
    public void setOriginalIssueId(String originalIssueId) {
        this.originalIssueId = originalIssueId == null ? null : originalIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UserInfo
     *
     * @return the value of Issues.UserInfo
     *
     * @mbg.generated
     */
    public String getUserInfo() {
        return userInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UserInfo
     *
     * @param userInfo the value for Issues.UserInfo
     *
     * @mbg.generated
     */
    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo == null ? null : userInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ToUser
     *
     * @return the value of Issues.ToUser
     *
     * @mbg.generated
     */
    public String getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ToUser
     *
     * @param toUser the value for Issues.ToUser
     *
     * @mbg.generated
     */
    public void setToUser(String toUser) {
        this.toUser = toUser == null ? null : toUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.FromTeam
     *
     * @return the value of Issues.FromTeam
     *
     * @mbg.generated
     */
    public String getFromTeam() {
        return fromTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.FromTeam
     *
     * @param fromTeam the value for Issues.FromTeam
     *
     * @mbg.generated
     */
    public void setFromTeam(String fromTeam) {
        this.fromTeam = fromTeam == null ? null : fromTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ToTeam
     *
     * @return the value of Issues.ToTeam
     *
     * @mbg.generated
     */
    public String getToTeam() {
        return toTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ToTeam
     *
     * @param toTeam the value for Issues.ToTeam
     *
     * @mbg.generated
     */
    public void setToTeam(String toTeam) {
        this.toTeam = toTeam == null ? null : toTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Content
     *
     * @return the value of Issues.Content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Content
     *
     * @param content the value for Issues.Content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ShareUser
     *
     * @return the value of Issues.ShareUser
     *
     * @mbg.generated
     */
    public String getShareUser() {
        return shareUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ShareUser
     *
     * @param shareUser the value for Issues.ShareUser
     *
     * @mbg.generated
     */
    public void setShareUser(String shareUser) {
        this.shareUser = shareUser == null ? null : shareUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Feedback
     *
     * @return the value of Issues.Feedback
     *
     * @mbg.generated
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Feedback
     *
     * @param feedback the value for Issues.Feedback
     *
     * @mbg.generated
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Scope
     *
     * @return the value of Issues.Scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Scope
     *
     * @param scope the value for Issues.Scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Images
     *
     * @return the value of Issues.Images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Images
     *
     * @param images the value for Issues.Images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Audios
     *
     * @return the value of Issues.Audios
     *
     * @mbg.generated
     */
    public String getAudios() {
        return audios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Audios
     *
     * @param audios the value for Issues.Audios
     *
     * @mbg.generated
     */
    public void setAudios(String audios) {
        this.audios = audios == null ? null : audios.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Invited
     *
     * @return the value of Issues.Invited
     *
     * @mbg.generated
     */
    public String getInvited() {
        return invited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Invited
     *
     * @param invited the value for Issues.Invited
     *
     * @mbg.generated
     */
    public void setInvited(String invited) {
        this.invited = invited == null ? null : invited.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.AdditionActivity
     *
     * @return the value of Issues.AdditionActivity
     *
     * @mbg.generated
     */
    public String getAdditionActivity() {
        return additionActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.AdditionActivity
     *
     * @param additionActivity the value for Issues.AdditionActivity
     *
     * @mbg.generated
     */
    public void setAdditionActivity(String additionActivity) {
        this.additionActivity = additionActivity == null ? null : additionActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.AdditionTeam
     *
     * @return the value of Issues.AdditionTeam
     *
     * @mbg.generated
     */
    public String getAdditionTeam() {
        return additionTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.AdditionTeam
     *
     * @param additionTeam the value for Issues.AdditionTeam
     *
     * @mbg.generated
     */
    public void setAdditionTeam(String additionTeam) {
        this.additionTeam = additionTeam == null ? null : additionTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", UID=").append(UID);
        sb.append(", userID=").append(userID);
        sb.append(", type=").append(type);
        sb.append(", title=").append(title);
        sb.append(", isShare=").append(isShare);
        sb.append(", shareUserID=").append(shareUserID);
        sb.append(", sort=").append(sort);
        sb.append(", praiseNum=").append(praiseNum);
        sb.append(", readNum=").append(readNum);
        sb.append(", collectNum=").append(collectNum);
        sb.append(", hotNum=").append(hotNum);
        sb.append(", isPublic=").append(isPublic);
        sb.append(", answerNum=").append(answerNum);
        sb.append(", tags=").append(tags);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", activeId=").append(activeId);
        sb.append(", teamId=").append(teamId);
        sb.append(", lastAnswerID=").append(lastAnswerID);
        sb.append(", reviewNum=").append(reviewNum);
        sb.append(", isAnonyMous=").append(isAnonyMous);
        sb.append(", sequence=").append(sequence);
        sb.append(", originalIssueId=").append(originalIssueId);
        sb.append(", userInfo=").append(userInfo);
        sb.append(", toUser=").append(toUser);
        sb.append(", fromTeam=").append(fromTeam);
        sb.append(", toTeam=").append(toTeam);
        sb.append(", content=").append(content);
        sb.append(", shareUser=").append(shareUser);
        sb.append(", feedback=").append(feedback);
        sb.append(", scope=").append(scope);
        sb.append(", images=").append(images);
        sb.append(", audios=").append(audios);
        sb.append(", invited=").append(invited);
        sb.append(", additionActivity=").append(additionActivity);
        sb.append(", additionTeam=").append(additionTeam);
        sb.append("]");
        return sb.toString();
    }
}