package com.ydb.entity.nochange;

import java.util.Date;

public class Issue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UID
     *
     * @mbggenerated
     */
    private String UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UserID
     *
     * @mbggenerated
     */
    private Long userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.IsShare
     *
     * @mbggenerated
     */
    private Boolean isShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.shareUserID
     *
     * @mbggenerated
     */
    private Long shareUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Sort
     *
     * @mbggenerated
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.PraiseNum
     *
     * @mbggenerated
     */
    private Short praiseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ReadNum
     *
     * @mbggenerated
     */
    private Short readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.CollectNum
     *
     * @mbggenerated
     */
    private Short collectNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.HotNum
     *
     * @mbggenerated
     */
    private Date hotNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.IsPublic
     *
     * @mbggenerated
     */
    private Boolean isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.AnswerNum
     *
     * @mbggenerated
     */
    private Short answerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UpdateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ActiveId
     *
     * @mbggenerated
     */
    private Long activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.TeamId
     *
     * @mbggenerated
     */
    private Integer teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.LastAnswerID
     *
     * @mbggenerated
     */
    private String lastAnswerID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ReviewNum
     *
     * @mbggenerated
     */
    private Short reviewNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.IsAnonyMous
     *
     * @mbggenerated
     */
    private Boolean isAnonyMous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Sequence
     *
     * @mbggenerated
     */
    private Long sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.originalIssueId
     *
     * @mbggenerated
     */
    private String originalIssueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UID
     *
     * @return the value of Issues.UID
     *
     * @mbggenerated
     */
    public String getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UID
     *
     * @param UID the value for Issues.UID
     *
     * @mbggenerated
     */
    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UserID
     *
     * @return the value of Issues.UserID
     *
     * @mbggenerated
     */
    public Long getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UserID
     *
     * @param userID the value for Issues.UserID
     *
     * @mbggenerated
     */
    public void setUserID(Long userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Type
     *
     * @return the value of Issues.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Type
     *
     * @param type the value for Issues.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Title
     *
     * @return the value of Issues.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Title
     *
     * @param title the value for Issues.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.IsShare
     *
     * @return the value of Issues.IsShare
     *
     * @mbggenerated
     */
    public Boolean getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.IsShare
     *
     * @param isShare the value for Issues.IsShare
     *
     * @mbggenerated
     */
    public void setIsShare(Boolean isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.shareUserID
     *
     * @return the value of Issues.shareUserID
     *
     * @mbggenerated
     */
    public Long getShareUserID() {
        return shareUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.shareUserID
     *
     * @param shareUserID the value for Issues.shareUserID
     *
     * @mbggenerated
     */
    public void setShareUserID(Long shareUserID) {
        this.shareUserID = shareUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Sort
     *
     * @return the value of Issues.Sort
     *
     * @mbggenerated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Sort
     *
     * @param sort the value for Issues.Sort
     *
     * @mbggenerated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.PraiseNum
     *
     * @return the value of Issues.PraiseNum
     *
     * @mbggenerated
     */
    public Short getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.PraiseNum
     *
     * @param praiseNum the value for Issues.PraiseNum
     *
     * @mbggenerated
     */
    public void setPraiseNum(Short praiseNum) {
        this.praiseNum = praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ReadNum
     *
     * @return the value of Issues.ReadNum
     *
     * @mbggenerated
     */
    public Short getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ReadNum
     *
     * @param readNum the value for Issues.ReadNum
     *
     * @mbggenerated
     */
    public void setReadNum(Short readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.CollectNum
     *
     * @return the value of Issues.CollectNum
     *
     * @mbggenerated
     */
    public Short getCollectNum() {
        return collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.CollectNum
     *
     * @param collectNum the value for Issues.CollectNum
     *
     * @mbggenerated
     */
    public void setCollectNum(Short collectNum) {
        this.collectNum = collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.HotNum
     *
     * @return the value of Issues.HotNum
     *
     * @mbggenerated
     */
    public Date getHotNum() {
        return hotNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.HotNum
     *
     * @param hotNum the value for Issues.HotNum
     *
     * @mbggenerated
     */
    public void setHotNum(Date hotNum) {
        this.hotNum = hotNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.IsPublic
     *
     * @return the value of Issues.IsPublic
     *
     * @mbggenerated
     */
    public Boolean getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.IsPublic
     *
     * @param isPublic the value for Issues.IsPublic
     *
     * @mbggenerated
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.AnswerNum
     *
     * @return the value of Issues.AnswerNum
     *
     * @mbggenerated
     */
    public Short getAnswerNum() {
        return answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.AnswerNum
     *
     * @param answerNum the value for Issues.AnswerNum
     *
     * @mbggenerated
     */
    public void setAnswerNum(Short answerNum) {
        this.answerNum = answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Tags
     *
     * @return the value of Issues.Tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Tags
     *
     * @param tags the value for Issues.Tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Status
     *
     * @return the value of Issues.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Status
     *
     * @param status the value for Issues.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UpdateTime
     *
     * @return the value of Issues.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UpdateTime
     *
     * @param updateTime the value for Issues.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.CreateTime
     *
     * @return the value of Issues.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.CreateTime
     *
     * @param createTime the value for Issues.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ActiveId
     *
     * @return the value of Issues.ActiveId
     *
     * @mbggenerated
     */
    public Long getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ActiveId
     *
     * @param activeId the value for Issues.ActiveId
     *
     * @mbggenerated
     */
    public void setActiveId(Long activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.TeamId
     *
     * @return the value of Issues.TeamId
     *
     * @mbggenerated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.TeamId
     *
     * @param teamId the value for Issues.TeamId
     *
     * @mbggenerated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.LastAnswerID
     *
     * @return the value of Issues.LastAnswerID
     *
     * @mbggenerated
     */
    public String getLastAnswerID() {
        return lastAnswerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.LastAnswerID
     *
     * @param lastAnswerID the value for Issues.LastAnswerID
     *
     * @mbggenerated
     */
    public void setLastAnswerID(String lastAnswerID) {
        this.lastAnswerID = lastAnswerID == null ? null : lastAnswerID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ReviewNum
     *
     * @return the value of Issues.ReviewNum
     *
     * @mbggenerated
     */
    public Short getReviewNum() {
        return reviewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ReviewNum
     *
     * @param reviewNum the value for Issues.ReviewNum
     *
     * @mbggenerated
     */
    public void setReviewNum(Short reviewNum) {
        this.reviewNum = reviewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.IsAnonyMous
     *
     * @return the value of Issues.IsAnonyMous
     *
     * @mbggenerated
     */
    public Boolean getIsAnonyMous() {
        return isAnonyMous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.IsAnonyMous
     *
     * @param isAnonyMous the value for Issues.IsAnonyMous
     *
     * @mbggenerated
     */
    public void setIsAnonyMous(Boolean isAnonyMous) {
        this.isAnonyMous = isAnonyMous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Sequence
     *
     * @return the value of Issues.Sequence
     *
     * @mbggenerated
     */
    public Long getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Sequence
     *
     * @param sequence the value for Issues.Sequence
     *
     * @mbggenerated
     */
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.originalIssueId
     *
     * @return the value of Issues.originalIssueId
     *
     * @mbggenerated
     */
    public String getOriginalIssueId() {
        return originalIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.originalIssueId
     *
     * @param originalIssueId the value for Issues.originalIssueId
     *
     * @mbggenerated
     */
    public void setOriginalIssueId(String originalIssueId) {
        this.originalIssueId = originalIssueId == null ? null : originalIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", UID=").append(UID);
        sb.append(", userID=").append(userID);
        sb.append(", type=").append(type);
        sb.append(", title=").append(title);
        sb.append(", isShare=").append(isShare);
        sb.append(", shareUserID=").append(shareUserID);
        sb.append(", sort=").append(sort);
        sb.append(", praiseNum=").append(praiseNum);
        sb.append(", readNum=").append(readNum);
        sb.append(", collectNum=").append(collectNum);
        sb.append(", hotNum=").append(hotNum);
        sb.append(", isPublic=").append(isPublic);
        sb.append(", answerNum=").append(answerNum);
        sb.append(", tags=").append(tags);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", activeId=").append(activeId);
        sb.append(", teamId=").append(teamId);
        sb.append(", lastAnswerID=").append(lastAnswerID);
        sb.append(", reviewNum=").append(reviewNum);
        sb.append(", isAnonyMous=").append(isAnonyMous);
        sb.append(", sequence=").append(sequence);
        sb.append(", originalIssueId=").append(originalIssueId);
        sb.append("]");
        return sb.toString();
    }
}