package com.ydb.entity.nochange;

public class IssueWithBLOBs extends Issue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.UserInfo
     *
     * @mbggenerated
     */
    private String userInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ToUser
     *
     * @mbggenerated
     */
    private String toUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.FromTeam
     *
     * @mbggenerated
     */
    private String fromTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ToTeam
     *
     * @mbggenerated
     */
    private String toTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.ShareUser
     *
     * @mbggenerated
     */
    private String shareUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Feedback
     *
     * @mbggenerated
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Images
     *
     * @mbggenerated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Audios
     *
     * @mbggenerated
     */
    private String audios;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.Invited
     *
     * @mbggenerated
     */
    private String invited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.AdditionActivity
     *
     * @mbggenerated
     */
    private String additionActivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Issues.AdditionTeam
     *
     * @mbggenerated
     */
    private String additionTeam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.UserInfo
     *
     * @return the value of Issues.UserInfo
     *
     * @mbggenerated
     */
    public String getUserInfo() {
        return userInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.UserInfo
     *
     * @param userInfo the value for Issues.UserInfo
     *
     * @mbggenerated
     */
    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo == null ? null : userInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ToUser
     *
     * @return the value of Issues.ToUser
     *
     * @mbggenerated
     */
    public String getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ToUser
     *
     * @param toUser the value for Issues.ToUser
     *
     * @mbggenerated
     */
    public void setToUser(String toUser) {
        this.toUser = toUser == null ? null : toUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.FromTeam
     *
     * @return the value of Issues.FromTeam
     *
     * @mbggenerated
     */
    public String getFromTeam() {
        return fromTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.FromTeam
     *
     * @param fromTeam the value for Issues.FromTeam
     *
     * @mbggenerated
     */
    public void setFromTeam(String fromTeam) {
        this.fromTeam = fromTeam == null ? null : fromTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ToTeam
     *
     * @return the value of Issues.ToTeam
     *
     * @mbggenerated
     */
    public String getToTeam() {
        return toTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ToTeam
     *
     * @param toTeam the value for Issues.ToTeam
     *
     * @mbggenerated
     */
    public void setToTeam(String toTeam) {
        this.toTeam = toTeam == null ? null : toTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Content
     *
     * @return the value of Issues.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Content
     *
     * @param content the value for Issues.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.ShareUser
     *
     * @return the value of Issues.ShareUser
     *
     * @mbggenerated
     */
    public String getShareUser() {
        return shareUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.ShareUser
     *
     * @param shareUser the value for Issues.ShareUser
     *
     * @mbggenerated
     */
    public void setShareUser(String shareUser) {
        this.shareUser = shareUser == null ? null : shareUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Feedback
     *
     * @return the value of Issues.Feedback
     *
     * @mbggenerated
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Feedback
     *
     * @param feedback the value for Issues.Feedback
     *
     * @mbggenerated
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Scope
     *
     * @return the value of Issues.Scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Scope
     *
     * @param scope the value for Issues.Scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Images
     *
     * @return the value of Issues.Images
     *
     * @mbggenerated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Images
     *
     * @param images the value for Issues.Images
     *
     * @mbggenerated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Audios
     *
     * @return the value of Issues.Audios
     *
     * @mbggenerated
     */
    public String getAudios() {
        return audios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Audios
     *
     * @param audios the value for Issues.Audios
     *
     * @mbggenerated
     */
    public void setAudios(String audios) {
        this.audios = audios == null ? null : audios.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.Invited
     *
     * @return the value of Issues.Invited
     *
     * @mbggenerated
     */
    public String getInvited() {
        return invited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.Invited
     *
     * @param invited the value for Issues.Invited
     *
     * @mbggenerated
     */
    public void setInvited(String invited) {
        this.invited = invited == null ? null : invited.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.AdditionActivity
     *
     * @return the value of Issues.AdditionActivity
     *
     * @mbggenerated
     */
    public String getAdditionActivity() {
        return additionActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.AdditionActivity
     *
     * @param additionActivity the value for Issues.AdditionActivity
     *
     * @mbggenerated
     */
    public void setAdditionActivity(String additionActivity) {
        this.additionActivity = additionActivity == null ? null : additionActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Issues.AdditionTeam
     *
     * @return the value of Issues.AdditionTeam
     *
     * @mbggenerated
     */
    public String getAdditionTeam() {
        return additionTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Issues.AdditionTeam
     *
     * @param additionTeam the value for Issues.AdditionTeam
     *
     * @mbggenerated
     */
    public void setAdditionTeam(String additionTeam) {
        this.additionTeam = additionTeam == null ? null : additionTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Issues
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userInfo=").append(userInfo);
        sb.append(", toUser=").append(toUser);
        sb.append(", fromTeam=").append(fromTeam);
        sb.append(", toTeam=").append(toTeam);
        sb.append(", content=").append(content);
        sb.append(", shareUser=").append(shareUser);
        sb.append(", feedback=").append(feedback);
        sb.append(", scope=").append(scope);
        sb.append(", images=").append(images);
        sb.append(", audios=").append(audios);
        sb.append(", invited=").append(invited);
        sb.append(", additionActivity=").append(additionActivity);
        sb.append(", additionTeam=").append(additionTeam);
        sb.append("]");
        return sb.toString();
    }
}